# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  pt: VALQUIRIA - Tratamento de tumores difusos do tronco cerebral
  en: VALKYRIE - Treatment of diffuse brainstem tumors
email: valkyr.ie@outlook.com
description:
  pt: VALQUIRIA é um caderno aberto de pesquisa de um projeto de ensaio clínico com o objetivo de estudar crianças e adolescentes com tumores difusos da ponte (tronco cerebral), uma doença grave sem terapia curativa estabelecida.
  en: VALKYRIE is a open science notebook for a clinical trial project to study children and adolescents with diffuse pontine (brainstem) tumors, a rare malignant brain tumor that has no curative therapy so far.
index:
  en: index.html
  pt: index-pt.html
feed:
  en: /feed.xml
  pt: /feed-pt.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fhcflx.github.io" # the base hostname & protocol for your site
exclude: [LICENSE.md,.bundle,.git,_site,Gemfile,Gemfile.lock,vendor]
twitter_username: valkyrie_trial
github_username:  fhcflx/valkyrie
defaults:
  -
    scope:
      path: "/valkyrie"
      type: "posts"
    values:
      layout: "default"
      author: "Francisco H. C. Felix"
      permalink: /:year/:title/
# Build settings
markdown: kramdown
