# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  pt: VALQUIRIA - Tratamento de tumores difusos do tronco cerebral
  en: VALKYRIE - Treatment of diffuse brainstem tumors
email: valkyr.ie@outlook.com
description:
  pt: VALQUIRIA é um modelo de caderno aberto de pesquisa para um projeto de ensaio clínico em neuro-oncologia pediátrica.
  en: VALKYRIE is a model for an open science notebook to a neuro-oncology clinical trial project.
index:
  en: index.html
  pt: index-pt.html
feed:
  en: /feed.xml
  pt: /feed-pt.xml
baseurl: "/valkyrie" # the subpath of your site, e.g. /blog
url: "http://fhcflx.github.io" # the base hostname & protocol for your site
exclude: [README.md,README-en.md,LICENSE.md,.bundle,.git,_site,Gemfile,Gemfile.lock,vendor,crew,docs]
twitter_username: valkyrie_trial
github_username:  fhcflx/valkyrie
defaults:
  -
    scope:
      path: "/_posts"
      type: "posts"
    values:
      layout: "default"
      author: "Francisco H. C. Felix"
      permalink: /:year/:title/

# Build settings
markdown: kramdown

plugins:
# - jekyll-seo-tag
  - jekyll-sitemap
