# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VALQUIRIA - Tratamento de tumores difusos do tronco cerebral
email: valkyr.ie@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  VALQUIRIA é um ensaio clínico que estuda o tratamento de crianças e adolescentes
  com tumores difusos da ponte (tronco cerebral), uma doença grave de
  difícil tratamento e sem terapia curativa estabelecida.
baseurl: "/valkyrie" # the subpath of your site, e.g. /blog
url: "http://fhcflx.github.io" # the base hostname & protocol for your site
twitter_username: valkyrie_trial
github_username:  fhcflx/valkyrie
twitter:
  consumer_key: zqU2B8FlUCc6HmHJyoP2pbn7k
  consumer_secret: 3u08pwR4WTrCiTipHvQzo4OZoV3Z6p7QLXbo8pkgWw2LeiQKkI
  access_token: 739525629746548737-JXA04QzF2BJrzGX7xgexxsPiULVLL5S
  access_token_secret: Js2QJ9yaLjlJw6MJOuuJdl50XAT38XklksiiEh0M7EG1G

# Build settings
markdown: kramdown
