# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  pt: VALQUIRIA - Tratamento de tumores difusos do tronco cerebral
  en: VALKYRIE - Treatment of diffuse brainstem tumors
email: valkyr.ie@outlook.com
description:
  pt: VALQUIRIA é um caderno aberto de pesquisa de um projeto de ensaio clínico com o objetivo de estudar crianças e adolescentes com tumores difusos da ponte (tronco cerebral), uma doença grave sem terapia curativa estabelecida.
  en: VALKYRIE is a open science notebook for a clinical trial project to study children and adolescents with diffuse pontine (brainstem) tumors, a rare malignant brain tumor that has no curative therapy so far.
index:
  en:
  pt: index-pt.html
feed:
  en: /feed.xml
  pt: /feed-pt.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fhcflx.github.io/valkyrie" # the base hostname & protocol for your site
exclude: [README.md,LICENSE.md,.bundle,.git,_site,Gemfile,Gemfile.lock]
twitter_username: valkyrie_trial
github_username:  fhcflx/valkyrie
twitter:
  consumer_key: zqU2B8FlUCc6HmHJyoP2pbn7k
  consumer_secret: 3u08pwR4WTrCiTipHvQzo4OZoV3Z6p7QLXbo8pkgWw2LeiQKkI
  access_token: 739525629746548737-JXA04QzF2BJrzGX7xgexxsPiULVLL5S
  access_token_secret: Js2QJ9yaLjlJw6MJOuuJdl50XAT38XklksiiEh0M7EG1G
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Francisco H. C. Felix"
      permalink: /:year/:title/

# Build settings
markdown: kramdown
