# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  pt: CAPNO - Um caderno aberto de pesquisas de neuro-oncologia
  en: NOOLN - an open lab notebook for neuro-oncology
email: neuronc.lab@outlook.com
description:
  pt: Este é um modelo de caderno aberto de pesquisa para um projeto de ensaio clínico em neuro-oncologia pediátrica.
  en: This is a model for an open science notebook to a neuro-oncology clinical trial project.
index:
  en: index.html
  pt: index-pt.html
feed:
  en: /feed.xml
  pt: /feed-pt.xml
baseurl: "/neuronc_lab" # the subpath of your site, e.g. /blog
url: "https://fhcflx.github.io" # the base hostname & protocol for your site
exclude: [README.md,README-en.md,LICENSE.md,.bundle,.git,_site,Gemfile,Gemfile.lock,vendor,crew,docs]
twitter_username: neuronc_lab
github_username:  fhcflx/neuronc_lab
collections:
  valkyrie:
    output: true
defaults:
  - scope:
      path: "/_posts"
      type: 
        en: "posts"
        pt: "postagens"
    values:
      layout: "default"
      author: "Francisco Felix"
      permalink: /:year/:title/

# Build settings
markdown: kramdown

plugins:
# - jekyll-seo-tag
  - jekyll-sitemap
