#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external --url-ignore "/#/"

echo 'baseurl: "/neuronc_lab"' >> _config.yml
bundle exec jekyll build

git add . && git commit -m "new update"
git filter-branch --subdirectory-filter _site --prune-empty
